# Generated by Django 2.1.7 on 2019-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190312_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(default='', max_length=300),
        ),
    ]
